version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: champ_local_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: champ_local_2025
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
